const fs = require("fs");

// ── Day68Tests.cs ──
fs.writeFileSync("BdStockOMS.Tests/Unit/Day68Tests.cs", [
"using BdStockOMS.API.Data;",
"using BdStockOMS.API.Models;",
"using Microsoft.EntityFrameworkCore;",
"using Xunit;",
"",
"namespace BdStockOMS.Tests.Unit;",
"",
"// ============================================================",
"//  Day 68 — RMSLimit Entity & Controller Logic Tests",
"// ============================================================",
"",
"public class Day68RMSLimitTests",
"{",
"    private AppDbContext CreateDb()",
"    {",
"        var opts = new DbContextOptionsBuilder<AppDbContext>()",
"            .UseInMemoryDatabase(Guid.NewGuid().ToString()).Options;",
"        return new AppDbContext(opts);",
"    }",
"",
"    private void SeedBrokerage(AppDbContext db, int id = 1)",
"    {",
"        db.BrokerageHouses.Add(new BrokerageHouse {",
"            Id = id, Name = \"Pioneer\", LicenseNumber = \"DSE-TM-0001\",",
"            Email = \"info@pioneer.com\", Phone = \"01700000000\",",
"            Address = \"Dhaka\", IsActive = true, CreatedAt = DateTime.UtcNow",
"        });",
"        db.SaveChanges();",
"    }",
"",
"    private RMSLimit MakeLimit(int brokerageId = 1, int? entityId = null,",
"        string entityType = \"Investor\", RMSLevel level = RMSLevel.Investor,",
"        RMSAction action = RMSAction.Block)",
"    => new RMSLimit",
"    {",
"        Level = level, EntityId = entityId, EntityType = entityType,",
"        BrokerageHouseId = brokerageId, MaxOrderValue = 5_000_000m,",
"        MaxDailyValue = 20_000_000m, MaxExposure = 50_000_000m,",
"        ConcentrationPct = 10m, ActionOnBreach = action,",
"        IsActive = true, CreatedAt = DateTime.UtcNow, UpdatedAt = DateTime.UtcNow",
"    };",
"",
"    // ── Entity defaults ──────────────────────────────────────",
"",
"    [Fact]",
"    public void RMSLimit_DefaultIsActive_IsTrue()",
"        => Assert.True(new RMSLimit().IsActive);",
"",
"    [Fact]",
"    public void RMSLimit_DefaultActionOnBreach_IsBlock()",
"        => Assert.Equal(RMSAction.Block, new RMSLimit().ActionOnBreach);",
"",
"    [Fact]",
"    public void RMSLevel_Investor_IsOne()",
"        => Assert.Equal(1, (int)RMSLevel.Investor);",
"",
"    [Fact]",
"    public void RMSLevel_Market_IsFive()",
"        => Assert.Equal(5, (int)RMSLevel.Market);",
"",
"    [Fact]",
"    public void RMSAction_Warn_IsOne()",
"        => Assert.Equal(1, (int)RMSAction.Warn);",
"",
"    [Fact]",
"    public void RMSAction_Block_IsTwo()",
"        => Assert.Equal(2, (int)RMSAction.Block);",
"",
"    [Fact]",
"    public void RMSAction_Freeze_IsThree()",
"        => Assert.Equal(3, (int)RMSAction.Freeze);",
"",
"    // ── DB persistence ───────────────────────────────────────",
"",
"    [Fact]",
"    public async Task RMSLimit_CanBeSaved_ToDb()",
"    {",
"        var db = CreateDb();",
"        SeedBrokerage(db);",
"        db.RMSLimits.Add(MakeLimit());",
"        await db.SaveChangesAsync();",
"        Assert.Equal(1, db.RMSLimits.Count());",
"    }",
"",
"    [Fact]",
"    public async Task RMSLimit_MultipleLevels_AllPersist()",
"    {",
"        var db = CreateDb();",
"        SeedBrokerage(db);",
"        db.RMSLimits.Add(MakeLimit(level: RMSLevel.Investor));",
"        db.RMSLimits.Add(MakeLimit(level: RMSLevel.Trader));",
"        db.RMSLimits.Add(MakeLimit(level: RMSLevel.Market));",
"        await db.SaveChangesAsync();",
"        Assert.Equal(3, db.RMSLimits.Count());",
"    }",
"",
"    [Fact]",
"    public async Task RMSLimit_FilterByEntityType_ReturnsCorrect()",
"    {",
"        var db = CreateDb();",
"        SeedBrokerage(db);",
"        db.RMSLimits.Add(MakeLimit(entityType: \"Investor\"));",
"        db.RMSLimits.Add(MakeLimit(entityType: \"Trader\"));",
"        db.RMSLimits.Add(MakeLimit(entityType: \"Market\"));",
"        await db.SaveChangesAsync();",
"        var investors = db.RMSLimits.Where(r => r.EntityType == \"Investor\").ToList();",
"        Assert.Single(investors);",
"    }",
"",
"    [Fact]",
"    public async Task RMSLimit_FilterByIsActive_ReturnsOnlyActive()",
"    {",
"        var db = CreateDb();",
"        SeedBrokerage(db);",
"        var active   = MakeLimit(); active.IsActive = true;",
"        var inactive = MakeLimit(); inactive.IsActive = false;",
"        db.RMSLimits.AddRange(active, inactive);",
"        await db.SaveChangesAsync();",
"        Assert.Single(db.RMSLimits.Where(r => r.IsActive));",
"    }",
"",
"    [Fact]",
"    public async Task RMSLimit_DeactivateExisting_WhenNewSet()",
"    {",
"        var db = CreateDb();",
"        SeedBrokerage(db);",
"        var old = MakeLimit(entityId: 5);",
"        db.RMSLimits.Add(old);",
"        await db.SaveChangesAsync();",
"",
"        // Simulate set-limit: deactivate old, add new",
"        var existing = db.RMSLimits.Where(r => r.EntityId == 5 && r.IsActive).ToList();",
"        foreach (var e in existing) e.IsActive = false;",
"        db.RMSLimits.Add(MakeLimit(entityId: 5));",
"        await db.SaveChangesAsync();",
"",
"        Assert.Equal(1, db.RMSLimits.Count(r => r.IsActive));",
"        Assert.Equal(2, db.RMSLimits.Count());",
"    }",
"",
"    [Fact]",
"    public async Task RMSLimit_FilterByBrokerageHouseId()",
"    {",
"        var db = CreateDb();",
"        SeedBrokerage(db, 1);",
"        SeedBrokerage(db, 2);",
"        db.RMSLimits.Add(MakeLimit(brokerageId: 1));",
"        db.RMSLimits.Add(MakeLimit(brokerageId: 2));",
"        await db.SaveChangesAsync();",
"        Assert.Single(db.RMSLimits.Where(r => r.BrokerageHouseId == 1));",
"    }",
"",
"    [Fact]",
"    public async Task RMSLimit_MaxOrderValue_Persists()",
"    {",
"        var db = CreateDb();",
"        SeedBrokerage(db);",
"        var limit = MakeLimit();",
"        limit.MaxOrderValue = 10_000_000m;",
"        db.RMSLimits.Add(limit);",
"        await db.SaveChangesAsync();",
"        Assert.Equal(10_000_000m, db.RMSLimits.First().MaxOrderValue);",
"    }",
"",
"    [Fact]",
"    public async Task RMSLimit_ConcentrationPct_Persists()",
"    {",
"        var db = CreateDb();",
"        SeedBrokerage(db);",
"        var limit = MakeLimit();",
"        limit.ConcentrationPct = 15m;",
"        db.RMSLimits.Add(limit);",
"        await db.SaveChangesAsync();",
"        Assert.Equal(15m, db.RMSLimits.First().ConcentrationPct);",
"    }",
"",
"    [Fact]",
"    public async Task RMSLimit_WarnAction_Persists()",
"    {",
"        var db = CreateDb();",
"        SeedBrokerage(db);",
"        db.RMSLimits.Add(MakeLimit(action: RMSAction.Warn));",
"        await db.SaveChangesAsync();",
"        Assert.Equal(RMSAction.Warn, db.RMSLimits.First().ActionOnBreach);",
"    }",
"",
"    [Fact]",
"    public async Task RMSLimit_FreezeAction_Persists()",
"    {",
"        var db = CreateDb();",
"        SeedBrokerage(db);",
"        db.RMSLimits.Add(MakeLimit(action: RMSAction.Freeze));",
"        await db.SaveChangesAsync();",
"        Assert.Equal(RMSAction.Freeze, db.RMSLimits.First().ActionOnBreach);",
"    }",
"",
"    [Fact]",
"    public async Task RMSLimit_EntityId_CanBeNull_ForGlobalLimit()",
"    {",
"        var db = CreateDb();",
"        SeedBrokerage(db);",
"        db.RMSLimits.Add(MakeLimit(entityId: null));",
"        await db.SaveChangesAsync();",
"        Assert.Null(db.RMSLimits.First().EntityId);",
"    }",
"",
"    [Fact]",
"    public async Task RMSLimit_SectorLevel_Persists()",
"    {",
"        var db = CreateDb();",
"        SeedBrokerage(db);",
"        db.RMSLimits.Add(MakeLimit(level: RMSLevel.Sector, entityType: \"Sector\"));",
"        await db.SaveChangesAsync();",
"        Assert.Equal(RMSLevel.Sector, db.RMSLimits.First().Level);",
"    }",
"}",
].join("\n"));
console.log("Day68Tests.cs written");

// ── Day log ──
fs.writeFileSync("docs/Day-68.md", [
"# Day 68 - Risk Management System (RMS) UI",
"",
"**Branch:** `day-68-rms-ui`",
"**Tests:** 895 (start) -> 910 (end) | +15 tests",
"**All tests:** 910 backend passing, 0 failures",
"",
"---",
"",
"## Summary",
"",
"| # | Goal | Status |",
"|---|------|--------|",
"| 1 | RMSManagementPage.tsx — full limit management UI | Done |",
"| 2 | Summary cards: Total/Investor/Block/Warn counts | Done |",
"| 3 | Tabs: All / Investor / Trader / Market+Sector | Done |",
"| 4 | Filter by brokerage + entity type | Done |",
"| 5 | Set Limit modal — Level, EntityType, Brokerage, Investor picker | Done |",
"| 6 | Action on Breach selector: Warn / Block / Freeze | Done |",
"| 7 | GET /api/rms/limits endpoint added to RMSController | Done |",
"| 8 | App.tsx route /rms wired to RMSManagementPage | Done |",
"| 9 | Day68Tests.cs — 15 RMSLimit entity + DB tests | Done |",
"| 10 | Build passing: 0 errors | Done |",
"",
"---",
"",
"## New API Endpoint",
"",
"| Method | Route | Description |",
"|--------|-------|-------------|",
"| GET | /api/rms/limits | All active RMS limits (filter: brokerageHouseId, entityType) |",
"",
"Existing endpoints used:",
"| POST | /api/rms/set-limit | Create/replace limit for entity |",
"| GET | /api/rms/investor/{id} | Limits for specific investor |",
"| GET | /api/rms/my-limits | Current user limits |",
"",
"---",
"",
"## RMS Limit Fields",
"",
"| Field | Type | Description |",
"|-------|------|-------------|",
"| Level | RMSLevel enum | Investor/Trader/Stock/Sector/Market/Exchange |",
"| EntityType | string | Matches Level name |",
"| EntityId | int? | null = global limit for all entities of this type |",
"| MaxOrderValue | decimal | Max single order in BDT |",
"| MaxDailyValue | decimal | Max total orders per day in BDT |",
"| MaxExposure | decimal | Max portfolio exposure in BDT |",
"| ConcentrationPct | decimal | Max % of portfolio in single stock |",
"| ActionOnBreach | RMSAction | Warn=1 / Block=2 / Freeze=3 |",
"",
"---",
"",
"## Test Count Progression",
"",
"| Day | Backend | Total | Notes |",
"|-----|---------|-------|-------|",
"| 67 | 895 | 895 | Start |",
"| 68 | 910 | 910 | +15 RMSLimit entity + DB tests |",
"",
"---",
"",
"## Next: Day 69 - T&S Multi-Symbol + Widget Drawer Drag-to-Reorder",
].join("\n"));
console.log("docs/Day-68.md written");
