// <auto-generated />
using System;
using BdStockOMS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BdStockOMS.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260309084144_Day30_TradeModelOrderStateMachine")]
    partial class Day30_TradeModelOrderStateMachine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BdStockOMS.API.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.BrokerageCommissionRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrokerageHouseId")
                        .HasColumnType("int");

                    b.Property<decimal>("BuyRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("SellRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("BrokerageHouseId");

                    b.ToTable("BrokerageCommissionRates");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.BrokerageHouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("BrokerageHouses");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.CommissionRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BuyRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CDBLRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DSEFeeRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("SellRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.ToTable("CommissionRates");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.CorporateAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("CorporateActions");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.FundRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("BrokerageHouseId")
                        .HasColumnType("int");

                    b.Property<int?>("CCDUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InvestorId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TraderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrokerageHouseId");

                    b.HasIndex("CCDUserId");

                    b.HasIndex("InvestorId");

                    b.HasIndex("TraderId");

                    b.ToTable("FundRequests");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.InvestorCommissionRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("BrokerageHouseId")
                        .HasColumnType("int");

                    b.Property<decimal>("BuyRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<int>("InvestorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<decimal>("SellRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("BrokerageHouseId");

                    b.HasIndex("InvestorId");

                    b.ToTable("InvestorCommissionRates");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.LoginHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FailureReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LoginHistories");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.MarketData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<int>("Trades")
                        .HasColumnType("int");

                    b.Property<decimal>("ValueInMillionTaka")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StockId", "Date", "Exchange")
                        .IsUnique();

                    b.ToTable("MarketData");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.NewsItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RelatedStockId")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RelatedStockId");

                    b.ToTable("NewsItems");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrokerageHouseId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ExecutionPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("InvestorId")
                        .HasColumnType("int");

                    b.Property<decimal?>("LimitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrderCategory")
                        .HasColumnType("int");

                    b.Property<int>("OrderType")
                        .HasColumnType("int");

                    b.Property<int>("PlacedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceAtOrder")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SettlementType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<int?>("TraderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrokerageHouseId");

                    b.HasIndex("InvestorId");

                    b.HasIndex("StockId");

                    b.HasIndex("TraderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.OrderAmendment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AmendedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NewPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("NewQuantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("OldPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("OldQuantity")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AmendedByUserId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderAmendments");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.OrderEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TriggeredBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderEvents");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.PasswordHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordHistories");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageBuyPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("BrokerageHouseId")
                        .HasColumnType("int");

                    b.Property<int>("InvestorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrokerageHouseId");

                    b.HasIndex("StockId");

                    b.HasIndex("InvestorId", "StockId")
                        .IsUnique();

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.RMSLimit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionOnBreach")
                        .HasColumnType("int");

                    b.Property<int>("BrokerageHouseId")
                        .HasColumnType("int");

                    b.Property<decimal>("ConcentrationPct")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxDailyValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("MaxExposure")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("MaxOrderValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BrokerageHouseId");

                    b.ToTable("RMSLimits");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "SuperAdmin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "BrokerageHouse"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 4,
                            Name = "CCD"
                        },
                        new
                        {
                            Id = 5,
                            Name = "ITSupport"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Trader"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Investor"
                        });
                });

            modelBuilder.Entity("BdStockOMS.API.Models.SectorConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxConcentrationPct")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("SectorCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SectorConfigs");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BoardLotSize")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<decimal>("Change")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ChangePercent")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CircuitBreakerHigh")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CircuitBreakerLow")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ClosePrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("HighPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("LastTradePrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LowPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("TradingCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("ValueInMillionTaka")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TradingCode", "Exchange")
                        .IsUnique();

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BoardLotSize = 1,
                            Category = 0,
                            Change = 0m,
                            ChangePercent = 0m,
                            CircuitBreakerHigh = 418.55m,
                            CircuitBreakerLow = 342.45m,
                            ClosePrice = 0m,
                            CompanyName = "Grameenphone Ltd",
                            Exchange = "DSE",
                            HighPrice = 0m,
                            IsActive = true,
                            LastTradePrice = 380.50m,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowPrice = 0m,
                            TradingCode = "GP",
                            ValueInMillionTaka = 0m,
                            Volume = 0L
                        },
                        new
                        {
                            Id = 2,
                            BoardLotSize = 1,
                            Category = 0,
                            Change = 0m,
                            ChangePercent = 0m,
                            CircuitBreakerHigh = 57.53m,
                            CircuitBreakerLow = 47.07m,
                            ClosePrice = 0m,
                            CompanyName = "BRAC Bank Ltd",
                            Exchange = "DSE",
                            HighPrice = 0m,
                            IsActive = true,
                            LastTradePrice = 52.30m,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowPrice = 0m,
                            TradingCode = "BRACBANK",
                            ValueInMillionTaka = 0m,
                            Volume = 0L
                        },
                        new
                        {
                            Id = 3,
                            BoardLotSize = 1,
                            Category = 0,
                            Change = 0m,
                            ChangePercent = 0m,
                            CircuitBreakerHigh = 236.50m,
                            CircuitBreakerLow = 193.50m,
                            ClosePrice = 0m,
                            CompanyName = "Square Pharmaceuticals Ltd",
                            Exchange = "DSE",
                            HighPrice = 0m,
                            IsActive = true,
                            LastTradePrice = 215.00m,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowPrice = 0m,
                            TradingCode = "SQURPHARMA",
                            ValueInMillionTaka = 0m,
                            Volume = 0L
                        },
                        new
                        {
                            Id = 4,
                            BoardLotSize = 1,
                            Category = 0,
                            Change = 0m,
                            ChangePercent = 0m,
                            CircuitBreakerHigh = 35.86m,
                            CircuitBreakerLow = 29.34m,
                            ClosePrice = 0m,
                            CompanyName = "Islami Bank Bangladesh Ltd",
                            Exchange = "DSE",
                            HighPrice = 0m,
                            IsActive = true,
                            LastTradePrice = 32.60m,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowPrice = 0m,
                            TradingCode = "ISLAMIBANK",
                            ValueInMillionTaka = 0m,
                            Volume = 0L
                        },
                        new
                        {
                            Id = 5,
                            BoardLotSize = 1,
                            Category = 0,
                            Change = 0m,
                            ChangePercent = 0m,
                            CircuitBreakerHigh = 108.35m,
                            CircuitBreakerLow = 88.65m,
                            ClosePrice = 0m,
                            CompanyName = "Dutch Bangla Bank Ltd",
                            Exchange = "DSE",
                            HighPrice = 0m,
                            IsActive = true,
                            LastTradePrice = 98.50m,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowPrice = 0m,
                            TradingCode = "DUTCHBANGL",
                            ValueInMillionTaka = 0m,
                            Volume = 0L
                        },
                        new
                        {
                            Id = 6,
                            BoardLotSize = 1,
                            Category = 0,
                            Change = 0m,
                            ChangePercent = 0m,
                            CircuitBreakerHigh = 1155.00m,
                            CircuitBreakerLow = 945.00m,
                            ClosePrice = 0m,
                            CompanyName = "Renata Ltd",
                            Exchange = "DSE",
                            HighPrice = 0m,
                            IsActive = true,
                            LastTradePrice = 1050.00m,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowPrice = 0m,
                            TradingCode = "RENATA",
                            ValueInMillionTaka = 0m,
                            Volume = 0L
                        },
                        new
                        {
                            Id = 7,
                            BoardLotSize = 1,
                            Category = 0,
                            Change = 0m,
                            ChangePercent = 0m,
                            CircuitBreakerHigh = 715.00m,
                            CircuitBreakerLow = 585.00m,
                            ClosePrice = 0m,
                            CompanyName = "British American Tobacco Bangladesh",
                            Exchange = "DSE",
                            HighPrice = 0m,
                            IsActive = true,
                            LastTradePrice = 650.00m,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowPrice = 0m,
                            TradingCode = "BATBC",
                            ValueInMillionTaka = 0m,
                            Volume = 0L
                        },
                        new
                        {
                            Id = 8,
                            BoardLotSize = 1,
                            Category = 0,
                            Change = 0m,
                            ChangePercent = 0m,
                            CircuitBreakerHigh = 2310.00m,
                            CircuitBreakerLow = 1890.00m,
                            ClosePrice = 0m,
                            CompanyName = "Marico Bangladesh Ltd",
                            Exchange = "DSE",
                            HighPrice = 0m,
                            IsActive = true,
                            LastTradePrice = 2100.00m,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowPrice = 0m,
                            TradingCode = "MARICO",
                            ValueInMillionTaka = 0m,
                            Volume = 0L
                        },
                        new
                        {
                            Id = 9,
                            BoardLotSize = 1,
                            Category = 0,
                            Change = 0m,
                            ChangePercent = 0m,
                            CircuitBreakerHigh = 1320.00m,
                            CircuitBreakerLow = 1080.00m,
                            ClosePrice = 0m,
                            CompanyName = "Berger Paints Bangladesh Ltd",
                            Exchange = "DSE",
                            HighPrice = 0m,
                            IsActive = true,
                            LastTradePrice = 1200.00m,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowPrice = 0m,
                            TradingCode = "BERGERPBL",
                            ValueInMillionTaka = 0m,
                            Volume = 0L
                        },
                        new
                        {
                            Id = 10,
                            BoardLotSize = 1,
                            Category = 0,
                            Change = 0m,
                            ChangePercent = 0m,
                            CircuitBreakerHigh = 31.24m,
                            CircuitBreakerLow = 25.56m,
                            ClosePrice = 0m,
                            CompanyName = "The City Bank Ltd",
                            Exchange = "DSE",
                            HighPrice = 0m,
                            IsActive = true,
                            LastTradePrice = 28.40m,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowPrice = 0m,
                            TradingCode = "CITYBANK",
                            ValueInMillionTaka = 0m,
                            Volume = 0L
                        },
                        new
                        {
                            Id = 11,
                            BoardLotSize = 1,
                            Category = 4,
                            Change = 0m,
                            ChangePercent = 0m,
                            CircuitBreakerHigh = 9.35m,
                            CircuitBreakerLow = 7.65m,
                            ClosePrice = 0m,
                            CompanyName = "Aamra Networks Ltd",
                            Exchange = "DSE",
                            HighPrice = 0m,
                            IsActive = true,
                            LastTradePrice = 8.50m,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowPrice = 0m,
                            TradingCode = "AAMRANET",
                            ValueInMillionTaka = 0m,
                            Volume = 0L
                        },
                        new
                        {
                            Id = 12,
                            BoardLotSize = 1,
                            Category = 0,
                            Change = 0m,
                            ChangePercent = 0m,
                            CircuitBreakerHigh = 418.00m,
                            CircuitBreakerLow = 342.00m,
                            ClosePrice = 0m,
                            CompanyName = "Grameenphone Ltd",
                            Exchange = "CSE",
                            HighPrice = 0m,
                            IsActive = true,
                            LastTradePrice = 380.00m,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowPrice = 0m,
                            TradingCode = "GP",
                            ValueInMillionTaka = 0m,
                            Volume = 0L
                        },
                        new
                        {
                            Id = 13,
                            BoardLotSize = 1,
                            Category = 0,
                            Change = 0m,
                            ChangePercent = 0m,
                            CircuitBreakerHigh = 57.31m,
                            CircuitBreakerLow = 46.89m,
                            ClosePrice = 0m,
                            CompanyName = "BRAC Bank Ltd",
                            Exchange = "CSE",
                            HighPrice = 0m,
                            IsActive = true,
                            LastTradePrice = 52.10m,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowPrice = 0m,
                            TradingCode = "BRACBANK",
                            ValueInMillionTaka = 0m,
                            Volume = 0L
                        },
                        new
                        {
                            Id = 14,
                            BoardLotSize = 1,
                            Category = 0,
                            Change = 0m,
                            ChangePercent = 0m,
                            CircuitBreakerHigh = 235.95m,
                            CircuitBreakerLow = 193.05m,
                            ClosePrice = 0m,
                            CompanyName = "Square Pharmaceuticals Ltd",
                            Exchange = "CSE",
                            HighPrice = 0m,
                            IsActive = true,
                            LastTradePrice = 214.50m,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowPrice = 0m,
                            TradingCode = "SQURPHARMA",
                            ValueInMillionTaka = 0m,
                            Volume = 0L
                        },
                        new
                        {
                            Id = 15,
                            BoardLotSize = 1,
                            Category = 0,
                            Change = 0m,
                            ChangePercent = 0m,
                            CircuitBreakerHigh = 35.64m,
                            CircuitBreakerLow = 29.16m,
                            ClosePrice = 0m,
                            CompanyName = "Islami Bank Bangladesh Ltd",
                            Exchange = "CSE",
                            HighPrice = 0m,
                            IsActive = true,
                            LastTradePrice = 32.40m,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowPrice = 0m,
                            TradingCode = "ISLAMIBANK",
                            ValueInMillionTaka = 0m,
                            Volume = 0L
                        },
                        new
                        {
                            Id = 16,
                            BoardLotSize = 1,
                            Category = 0,
                            Change = 0m,
                            ChangePercent = 0m,
                            CircuitBreakerHigh = 108.02m,
                            CircuitBreakerLow = 88.38m,
                            ClosePrice = 0m,
                            CompanyName = "Dutch Bangla Bank Ltd",
                            Exchange = "CSE",
                            HighPrice = 0m,
                            IsActive = true,
                            LastTradePrice = 98.20m,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowPrice = 0m,
                            TradingCode = "DUTCHBANGL",
                            ValueInMillionTaka = 0m,
                            Volume = 0L
                        });
                });

            modelBuilder.Entity("BdStockOMS.API.Models.SystemLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemLogs");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrokerageHouseId")
                        .HasColumnType("int");

                    b.Property<string>("ExchangeTradeId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("InvestorId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TradedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BrokerageHouseId");

                    b.HasIndex("InvestorId");

                    b.HasIndex("OrderId");

                    b.HasIndex("StockId");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.TraderReassignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrokerageHouseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InvestorId")
                        .HasColumnType("int");

                    b.Property<int>("NewTraderId")
                        .HasColumnType("int");

                    b.Property<int?>("OldTraderId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReassignedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrokerageHouseId");

                    b.HasIndex("InvestorId");

                    b.HasIndex("NewTraderId");

                    b.HasIndex("OldTraderId");

                    b.HasIndex("ReassignedByUserId");

                    b.ToTable("TraderReassignments");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.TrustedDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TrustedDevices");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.TwoFactorOtp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TwoFactorOtps");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountType")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedTraderId")
                        .HasColumnType("int");

                    b.Property<string>("BONumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("BrokerageHouseId")
                        .HasColumnType("int");

                    b.Property<decimal>("CashBalance")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("int");

                    b.Property<bool>("ForcePasswordChange")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBOAccountActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockoutUntil")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MarginLimit")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("MarginUsed")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("PasswordChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTraderId");

                    b.HasIndex("BrokerageHouseId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.UserSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.Watchlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Watchlists");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.WatchlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<int>("WatchlistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.HasIndex("WatchlistId", "StockId")
                        .IsUnique();

                    b.ToTable("WatchlistItems");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.AuditLog", b =>
                {
                    b.HasOne("BdStockOMS.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.BrokerageCommissionRate", b =>
                {
                    b.HasOne("BdStockOMS.API.Models.BrokerageHouse", "BrokerageHouse")
                        .WithMany()
                        .HasForeignKey("BrokerageHouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BrokerageHouse");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.CorporateAction", b =>
                {
                    b.HasOne("BdStockOMS.API.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.FundRequest", b =>
                {
                    b.HasOne("BdStockOMS.API.Models.BrokerageHouse", "BrokerageHouse")
                        .WithMany()
                        .HasForeignKey("BrokerageHouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BdStockOMS.API.Models.User", "CCDUser")
                        .WithMany()
                        .HasForeignKey("CCDUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BdStockOMS.API.Models.User", "Investor")
                        .WithMany()
                        .HasForeignKey("InvestorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BdStockOMS.API.Models.User", "Trader")
                        .WithMany()
                        .HasForeignKey("TraderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BrokerageHouse");

                    b.Navigation("CCDUser");

                    b.Navigation("Investor");

                    b.Navigation("Trader");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.InvestorCommissionRate", b =>
                {
                    b.HasOne("BdStockOMS.API.Models.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BdStockOMS.API.Models.BrokerageHouse", "BrokerageHouse")
                        .WithMany()
                        .HasForeignKey("BrokerageHouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BdStockOMS.API.Models.User", "Investor")
                        .WithMany()
                        .HasForeignKey("InvestorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("BrokerageHouse");

                    b.Navigation("Investor");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.LoginHistory", b =>
                {
                    b.HasOne("BdStockOMS.API.Models.User", "User")
                        .WithMany("LoginHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.MarketData", b =>
                {
                    b.HasOne("BdStockOMS.API.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.NewsItem", b =>
                {
                    b.HasOne("BdStockOMS.API.Models.Stock", "RelatedStock")
                        .WithMany()
                        .HasForeignKey("RelatedStockId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RelatedStock");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.Notification", b =>
                {
                    b.HasOne("BdStockOMS.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.Order", b =>
                {
                    b.HasOne("BdStockOMS.API.Models.BrokerageHouse", "BrokerageHouse")
                        .WithMany()
                        .HasForeignKey("BrokerageHouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BdStockOMS.API.Models.User", "Investor")
                        .WithMany("Orders")
                        .HasForeignKey("InvestorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BdStockOMS.API.Models.Stock", "Stock")
                        .WithMany("Orders")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BdStockOMS.API.Models.User", "Trader")
                        .WithMany()
                        .HasForeignKey("TraderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BrokerageHouse");

                    b.Navigation("Investor");

                    b.Navigation("Stock");

                    b.Navigation("Trader");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.OrderAmendment", b =>
                {
                    b.HasOne("BdStockOMS.API.Models.User", "AmendedBy")
                        .WithMany()
                        .HasForeignKey("AmendedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BdStockOMS.API.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AmendedBy");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.OrderEvent", b =>
                {
                    b.HasOne("BdStockOMS.API.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.PasswordHistory", b =>
                {
                    b.HasOne("BdStockOMS.API.Models.User", "User")
                        .WithMany("PasswordHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.Portfolio", b =>
                {
                    b.HasOne("BdStockOMS.API.Models.BrokerageHouse", "BrokerageHouse")
                        .WithMany()
                        .HasForeignKey("BrokerageHouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BdStockOMS.API.Models.User", "Investor")
                        .WithMany("Portfolios")
                        .HasForeignKey("InvestorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BdStockOMS.API.Models.Stock", "Stock")
                        .WithMany("Portfolios")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BrokerageHouse");

                    b.Navigation("Investor");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.RMSLimit", b =>
                {
                    b.HasOne("BdStockOMS.API.Models.BrokerageHouse", "BrokerageHouse")
                        .WithMany()
                        .HasForeignKey("BrokerageHouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BrokerageHouse");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.RefreshToken", b =>
                {
                    b.HasOne("BdStockOMS.API.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.SystemSetting", b =>
                {
                    b.HasOne("BdStockOMS.API.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.Trade", b =>
                {
                    b.HasOne("BdStockOMS.API.Models.BrokerageHouse", "BrokerageHouse")
                        .WithMany()
                        .HasForeignKey("BrokerageHouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BdStockOMS.API.Models.User", "Investor")
                        .WithMany()
                        .HasForeignKey("InvestorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BdStockOMS.API.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BdStockOMS.API.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BrokerageHouse");

                    b.Navigation("Investor");

                    b.Navigation("Order");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.TraderReassignment", b =>
                {
                    b.HasOne("BdStockOMS.API.Models.BrokerageHouse", "BrokerageHouse")
                        .WithMany()
                        .HasForeignKey("BrokerageHouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BdStockOMS.API.Models.User", "Investor")
                        .WithMany()
                        .HasForeignKey("InvestorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BdStockOMS.API.Models.User", "NewTrader")
                        .WithMany()
                        .HasForeignKey("NewTraderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BdStockOMS.API.Models.User", "OldTrader")
                        .WithMany()
                        .HasForeignKey("OldTraderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BdStockOMS.API.Models.User", "ReassignedBy")
                        .WithMany()
                        .HasForeignKey("ReassignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BrokerageHouse");

                    b.Navigation("Investor");

                    b.Navigation("NewTrader");

                    b.Navigation("OldTrader");

                    b.Navigation("ReassignedBy");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.TrustedDevice", b =>
                {
                    b.HasOne("BdStockOMS.API.Models.User", "User")
                        .WithMany("TrustedDevices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.TwoFactorOtp", b =>
                {
                    b.HasOne("BdStockOMS.API.Models.User", "User")
                        .WithMany("TwoFactorOtps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.User", b =>
                {
                    b.HasOne("BdStockOMS.API.Models.User", "AssignedTrader")
                        .WithMany()
                        .HasForeignKey("AssignedTraderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BdStockOMS.API.Models.BrokerageHouse", "BrokerageHouse")
                        .WithMany("Users")
                        .HasForeignKey("BrokerageHouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BdStockOMS.API.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedTrader");

                    b.Navigation("BrokerageHouse");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.UserSession", b =>
                {
                    b.HasOne("BdStockOMS.API.Models.User", "User")
                        .WithMany("UserSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.Watchlist", b =>
                {
                    b.HasOne("BdStockOMS.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.WatchlistItem", b =>
                {
                    b.HasOne("BdStockOMS.API.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BdStockOMS.API.Models.Watchlist", "Watchlist")
                        .WithMany("Items")
                        .HasForeignKey("WatchlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");

                    b.Navigation("Watchlist");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.BrokerageHouse", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.Stock", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Portfolios");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.User", b =>
                {
                    b.Navigation("LoginHistories");

                    b.Navigation("Orders");

                    b.Navigation("PasswordHistories");

                    b.Navigation("Portfolios");

                    b.Navigation("RefreshTokens");

                    b.Navigation("TrustedDevices");

                    b.Navigation("TwoFactorOtps");

                    b.Navigation("UserSessions");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.Watchlist", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
