// <auto-generated />
using System;
using BdStockOMS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BdStockOMS.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BdStockOMS.API.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.BrokerageHouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("BrokerageHouses");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("BrokerageHouseId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ExecutionPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("InvestorId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrderType")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceAtOrder")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<int?>("TraderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrokerageHouseId");

                    b.HasIndex("InvestorId");

                    b.HasIndex("StockId");

                    b.HasIndex("TraderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "BrokerageHouse"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "CCD"
                        },
                        new
                        {
                            Id = 4,
                            Name = "ITSupport"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Trader"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Investor"
                        });
                });

            modelBuilder.Entity("BdStockOMS.API.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Change")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ChangePercent")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ClosePrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("HighPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("LastTradePrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LowPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("TradingCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("ValueInMillionTaka")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TradingCode", "Exchange")
                        .IsUnique();

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Change = 0m,
                            ChangePercent = 0m,
                            ClosePrice = 0m,
                            CompanyName = "Grameenphone Ltd",
                            Exchange = "DSE",
                            HighPrice = 0m,
                            IsActive = true,
                            LastTradePrice = 380.50m,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowPrice = 0m,
                            TradingCode = "GP",
                            ValueInMillionTaka = 0m,
                            Volume = 0L
                        },
                        new
                        {
                            Id = 2,
                            Change = 0m,
                            ChangePercent = 0m,
                            ClosePrice = 0m,
                            CompanyName = "BRAC Bank Ltd",
                            Exchange = "DSE",
                            HighPrice = 0m,
                            IsActive = true,
                            LastTradePrice = 52.30m,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowPrice = 0m,
                            TradingCode = "BRACBANK",
                            ValueInMillionTaka = 0m,
                            Volume = 0L
                        },
                        new
                        {
                            Id = 3,
                            Change = 0m,
                            ChangePercent = 0m,
                            ClosePrice = 0m,
                            CompanyName = "Square Pharmaceuticals Ltd",
                            Exchange = "DSE",
                            HighPrice = 0m,
                            IsActive = true,
                            LastTradePrice = 215.00m,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowPrice = 0m,
                            TradingCode = "SQURPHARMA",
                            ValueInMillionTaka = 0m,
                            Volume = 0L
                        },
                        new
                        {
                            Id = 4,
                            Change = 0m,
                            ChangePercent = 0m,
                            ClosePrice = 0m,
                            CompanyName = "Islami Bank Bangladesh Ltd",
                            Exchange = "DSE",
                            HighPrice = 0m,
                            IsActive = true,
                            LastTradePrice = 32.60m,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowPrice = 0m,
                            TradingCode = "ISLAMIBANK",
                            ValueInMillionTaka = 0m,
                            Volume = 0L
                        },
                        new
                        {
                            Id = 5,
                            Change = 0m,
                            ChangePercent = 0m,
                            ClosePrice = 0m,
                            CompanyName = "Dutch Bangla Bank Ltd",
                            Exchange = "DSE",
                            HighPrice = 0m,
                            IsActive = true,
                            LastTradePrice = 98.50m,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowPrice = 0m,
                            TradingCode = "DUTCHBANGL",
                            ValueInMillionTaka = 0m,
                            Volume = 0L
                        },
                        new
                        {
                            Id = 6,
                            Change = 0m,
                            ChangePercent = 0m,
                            ClosePrice = 0m,
                            CompanyName = "Renata Ltd",
                            Exchange = "DSE",
                            HighPrice = 0m,
                            IsActive = true,
                            LastTradePrice = 1050.00m,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowPrice = 0m,
                            TradingCode = "RENATA",
                            ValueInMillionTaka = 0m,
                            Volume = 0L
                        },
                        new
                        {
                            Id = 7,
                            Change = 0m,
                            ChangePercent = 0m,
                            ClosePrice = 0m,
                            CompanyName = "British American Tobacco Bangladesh",
                            Exchange = "DSE",
                            HighPrice = 0m,
                            IsActive = true,
                            LastTradePrice = 650.00m,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowPrice = 0m,
                            TradingCode = "BATBC",
                            ValueInMillionTaka = 0m,
                            Volume = 0L
                        },
                        new
                        {
                            Id = 8,
                            Change = 0m,
                            ChangePercent = 0m,
                            ClosePrice = 0m,
                            CompanyName = "Marico Bangladesh Ltd",
                            Exchange = "DSE",
                            HighPrice = 0m,
                            IsActive = true,
                            LastTradePrice = 2100.00m,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowPrice = 0m,
                            TradingCode = "MARICO",
                            ValueInMillionTaka = 0m,
                            Volume = 0L
                        },
                        new
                        {
                            Id = 9,
                            Change = 0m,
                            ChangePercent = 0m,
                            ClosePrice = 0m,
                            CompanyName = "Berger Paints Bangladesh Ltd",
                            Exchange = "DSE",
                            HighPrice = 0m,
                            IsActive = true,
                            LastTradePrice = 1200.00m,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowPrice = 0m,
                            TradingCode = "BERGERPBL",
                            ValueInMillionTaka = 0m,
                            Volume = 0L
                        },
                        new
                        {
                            Id = 10,
                            Change = 0m,
                            ChangePercent = 0m,
                            ClosePrice = 0m,
                            CompanyName = "The City Bank Ltd",
                            Exchange = "DSE",
                            HighPrice = 0m,
                            IsActive = true,
                            LastTradePrice = 28.40m,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowPrice = 0m,
                            TradingCode = "CITYBANK",
                            ValueInMillionTaka = 0m,
                            Volume = 0L
                        },
                        new
                        {
                            Id = 11,
                            Change = 0m,
                            ChangePercent = 0m,
                            ClosePrice = 0m,
                            CompanyName = "Grameenphone Ltd",
                            Exchange = "CSE",
                            HighPrice = 0m,
                            IsActive = true,
                            LastTradePrice = 380.00m,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowPrice = 0m,
                            TradingCode = "GP",
                            ValueInMillionTaka = 0m,
                            Volume = 0L
                        },
                        new
                        {
                            Id = 12,
                            Change = 0m,
                            ChangePercent = 0m,
                            ClosePrice = 0m,
                            CompanyName = "BRAC Bank Ltd",
                            Exchange = "CSE",
                            HighPrice = 0m,
                            IsActive = true,
                            LastTradePrice = 52.10m,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowPrice = 0m,
                            TradingCode = "BRACBANK",
                            ValueInMillionTaka = 0m,
                            Volume = 0L
                        },
                        new
                        {
                            Id = 13,
                            Change = 0m,
                            ChangePercent = 0m,
                            ClosePrice = 0m,
                            CompanyName = "Square Pharmaceuticals Ltd",
                            Exchange = "CSE",
                            HighPrice = 0m,
                            IsActive = true,
                            LastTradePrice = 214.50m,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowPrice = 0m,
                            TradingCode = "SQURPHARMA",
                            ValueInMillionTaka = 0m,
                            Volume = 0L
                        },
                        new
                        {
                            Id = 14,
                            Change = 0m,
                            ChangePercent = 0m,
                            ClosePrice = 0m,
                            CompanyName = "Islami Bank Bangladesh Ltd",
                            Exchange = "CSE",
                            HighPrice = 0m,
                            IsActive = true,
                            LastTradePrice = 32.40m,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowPrice = 0m,
                            TradingCode = "ISLAMIBANK",
                            ValueInMillionTaka = 0m,
                            Volume = 0L
                        },
                        new
                        {
                            Id = 15,
                            Change = 0m,
                            ChangePercent = 0m,
                            ClosePrice = 0m,
                            CompanyName = "Dutch Bangla Bank Ltd",
                            Exchange = "CSE",
                            HighPrice = 0m,
                            IsActive = true,
                            LastTradePrice = 98.20m,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowPrice = 0m,
                            TradingCode = "DUTCHBANGL",
                            ValueInMillionTaka = 0m,
                            Volume = 0L
                        });
                });

            modelBuilder.Entity("BdStockOMS.API.Models.SystemLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemLogs");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedTraderId")
                        .HasColumnType("int");

                    b.Property<int>("BrokerageHouseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTraderId");

                    b.HasIndex("BrokerageHouseId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.AuditLog", b =>
                {
                    b.HasOne("BdStockOMS.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.Order", b =>
                {
                    b.HasOne("BdStockOMS.API.Models.BrokerageHouse", "BrokerageHouse")
                        .WithMany()
                        .HasForeignKey("BrokerageHouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BdStockOMS.API.Models.User", "Investor")
                        .WithMany("Orders")
                        .HasForeignKey("InvestorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BdStockOMS.API.Models.Stock", "Stock")
                        .WithMany("Orders")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BdStockOMS.API.Models.User", "Trader")
                        .WithMany()
                        .HasForeignKey("TraderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BrokerageHouse");

                    b.Navigation("Investor");

                    b.Navigation("Stock");

                    b.Navigation("Trader");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.User", b =>
                {
                    b.HasOne("BdStockOMS.API.Models.User", "AssignedTrader")
                        .WithMany()
                        .HasForeignKey("AssignedTraderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BdStockOMS.API.Models.BrokerageHouse", "BrokerageHouse")
                        .WithMany("Users")
                        .HasForeignKey("BrokerageHouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BdStockOMS.API.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedTrader");

                    b.Navigation("BrokerageHouse");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.BrokerageHouse", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.Stock", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BdStockOMS.API.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
