// @ts-nocheck
import { useEffect, useState } from 'react';
import { getBrokerages, getOrderSummaryReport, getTopInvestorsReport, getCommissionReport, getFundRequestReport } from '@/api/client';

const mono = '"JetBrains Mono",monospace';
const col  = (v) => `var(${v})`;
const fmt  = (n) => '৳' + Number(n||0).toLocaleString('en-BD',{minimumFractionDigits:2});
const fmtN = (n) => Number(n||0).toLocaleString('en-BD');

// ── CSV Export helper ────────────────────────────────────────
function exportCSV(filename, headers, rows) {
  const csv = [headers.join(','), ...rows.map(r => r.map(v => `"${String(v).replace(/"/g,'""')}"`).join(','))].join('\n');
  const blob = new Blob([csv], {type:'text/csv;charset=utf-8;'});
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
}

// ── Print / PDF helper ───────────────────────────────────────
function printReport(title, content) {
  const w = window.open('', '_blank');
  w.document.write(`
    <html><head><title>${title}</title>
    <style>body{font-family:Arial,sans-serif;font-size:12px;padding:20px}
    h1{font-size:16px;margin-bottom:4px}
    .meta{color:#666;font-size:11px;margin-bottom:16px}
    table{width:100%;border-collapse:collapse;margin-top:12px}
    th{background:#f0f0f0;padding:8px;text-align:left;font-size:11px;border:1px solid #ddd}
    td{padding:7px 8px;border:1px solid #eee;font-size:11px}
    tr:nth-child(even){background:#fafafa}
    .footer{margin-top:20px;font-size:10px;color:#999;border-top:1px solid #ddd;padding-top:8px}
    </style></head><body>${content}
    <div class='footer'>Generated by BdStockOMS • ${new Date().toLocaleString('en-BD')} • Confidential</div>
    </body></html>`,
  );
  w.document.close();
  setTimeout(() => w.print(), 300);
}

const Card = ({label, value, color='var(--t-accent)', sub=''}) => (
  <div style={{background:col('--t-panel'),border:`1px solid ${col('--t-border')}`,borderRadius:10,padding:'16px 20px'}}>
    <div style={{fontSize:10,color:col('--t-text3'),fontFamily:mono,textTransform:'uppercase',marginBottom:6}}>{label}</div>
    <div style={{fontSize:24,fontWeight:800,fontFamily:mono,color}}>{value}</div>
    {sub&&<div style={{fontSize:10,color:col('--t-text3'),marginTop:4}}>{sub}</div>}
  </div>
);

const TABS = [
  {id:'orders',     label:'Trade Orders'},
  {id:'commission', label:'Commission'},
  {id:'investors',  label:'Top Investors'},
  {id:'funds',      label:'Fund Requests'},
];

export default function ReportsPage() {
  const [tab,setTab]             = useState('orders');
  const [brokerages,setBrokerages] = useState([]);
  const [bid,setBid]             = useState('1');
  const [from,setFrom]           = useState(new Date(Date.now()-30*86400000).toISOString().slice(0,10));
  const [to,setTo]               = useState(new Date().toISOString().slice(0,10));
  const [data,setData]           = useState(null);
  const [loading,setLoading]     = useState(false);
  const [topN,setTopN]           = useState(10);

  useEffect(()=>{ getBrokerages().then(b=>setBrokerages(Array.isArray(b)?b:[])); },[]);

  const load = async () => {
    setLoading(true); setData(null);
    try {
      let d;
      if(tab==='orders')     d = await getOrderSummaryReport(bid,from,to);
      else if(tab==='commission') d = await getCommissionReport(bid,from,to);
      else if(tab==='investors')  d = await getTopInvestorsReport(bid,from,to,topN);
      else if(tab==='funds')      d = await getFundRequestReport(bid,from,to);
      setData(d);
    } finally { setLoading(false); }
  };

  useEffect(()=>{ load(); },[tab,bid]);

  const selStyle = {background:col('--t-hover'),border:`1px solid ${col('--t-border')}`,borderRadius:6,padding:'7px 10px',color:col('--t-text1'),fontSize:12,fontFamily:mono,outline:'none'};
  const inpStyle = {...selStyle};

  // ── CSV exports ─────────────────────────────────────────
  const exportOrders = () => {
    if(!data) return;
    exportCSV(`orders_report_${from}_${to}.csv`,
      ['Metric','Value'],
      [['Total Orders',data.totalOrders],['Buy Orders',data.buyOrders],['Sell Orders',data.sellOrders],
       ['Pending',data.pendingOrders],['Executed',data.executedOrders],['Cancelled',data.cancelledOrders],
       ['Rejected',data.rejectedOrders],['Total Value (৳)',data.totalOrderValue]]
    );
  };
  const exportCommission = () => {
    if(!data) return;
    exportCSV(`commission_report_${from}_${to}.csv`,
      ['Metric','Value'],
      [['Total Executed Orders',data.totalExecutedOrders],['Total Traded Value (৳)',data.totalTradedValue],['Estimated Commission (৳)',data.estimatedCommission]]
    );
  };
  const exportInvestors = () => {
    if(!data || !Array.isArray(data)) return;
    exportCSV(`top_investors_${from}_${to}.csv`,
      ['Rank','Investor','Email','Total Orders','Executed','Traded Value (৳)'],
      data.map((inv,i)=>[i+1,inv.investorName,inv.email,inv.totalOrders,inv.executedOrders,inv.totalTradedValue])
    );
  };
  const exportFunds = () => {
    if(!data) return;
    exportCSV(`fund_requests_${from}_${to}.csv`,
      ['Metric','Value'],
      [['Total Requests',data.totalRequests],['Pending',data.pendingRequests],['Completed',data.completedRequests],
       ['Rejected',data.rejectedRequests],['Total Completed Amount (৳)',data.totalCompletedAmount]]
    );
  };

  // ── Print exports ────────────────────────────────────────
  const printOrders = () => {
    if(!data) return;
    const brokName = brokerages.find(b=>String(b.id)===String(bid))?.name || 'Brokerage';
    printReport('Trade Orders Report', `
      <h1>Trade Orders Report</h1>
      <div class='meta'>${brokName} | ${from} to ${to}</div>
      <table><tr><th>Metric</th><th>Value</th></tr>
      <tr><td>Total Orders</td><td>${fmtN(data.totalOrders)}</td></tr>
      <tr><td>Buy Orders</td><td>${fmtN(data.buyOrders)}</td></tr>
      <tr><td>Sell Orders</td><td>${fmtN(data.sellOrders)}</td></tr>
      <tr><td>Executed</td><td>${fmtN(data.executedOrders)}</td></tr>
      <tr><td>Pending</td><td>${fmtN(data.pendingOrders)}</td></tr>
      <tr><td>Cancelled</td><td>${fmtN(data.cancelledOrders)}</td></tr>
      <tr><td>Rejected</td><td>${fmtN(data.rejectedOrders)}</td></tr>
      <tr><td><strong>Total Order Value</strong></td><td><strong>${fmt(data.totalOrderValue)}</strong></td></tr>
      </table>
    `);
  };

  return (
    <div style={{padding:24,color:col('--t-text1'),minHeight:'100vh'}}>
      {/* Header */}
      <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:20}}>
        <div>
          <div style={{fontSize:20,fontWeight:800,fontFamily:mono}}>Reports</div>
          <div style={{fontSize:12,color:col('--t-text3'),marginTop:2}}>Trade · Commission · Investors · Fund Requests</div>
        </div>
        <div style={{display:'flex',gap:8}}>
          <button onClick={tab==='orders'?exportOrders:tab==='commission'?exportCommission:tab==='investors'?exportInvestors:exportFunds}
            style={{padding:'8px 14px',background:'rgba(0,212,170,0.15)',color:'#00D4AA',border:'1px solid rgba(0,212,170,0.3)',borderRadius:7,fontWeight:700,fontSize:12,fontFamily:mono,cursor:'pointer'}}>
            ↓ CSV
          </button>
          <button onClick={tab==='orders'?printOrders:()=>{}}
            style={{padding:'8px 14px',background:'rgba(100,180,255,0.15)',color:'#64B4FF',border:'1px solid rgba(100,180,255,0.3)',borderRadius:7,fontWeight:700,fontSize:12,fontFamily:mono,cursor:'pointer'}}>
            🖨 Print / PDF
          </button>
        </div>
      </div>

      {/* Filters */}
      <div style={{display:'flex',gap:12,marginBottom:20,flexWrap:'wrap',alignItems:'center'}}>
        <div style={{display:'flex',flexDirection:'column',gap:4}}>
          <label style={{fontSize:10,color:col('--t-text3'),fontFamily:mono,textTransform:'uppercase'}}>Brokerage</label>
          <select value={bid} onChange={e=>setBid(e.target.value)} style={selStyle}>
            {brokerages.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}
          </select>
        </div>
        <div style={{display:'flex',flexDirection:'column',gap:4}}>
          <label style={{fontSize:10,color:col('--t-text3'),fontFamily:mono,textTransform:'uppercase'}}>From</label>
          <input type='date' value={from} onChange={e=>setFrom(e.target.value)} style={inpStyle}/>
        </div>
        <div style={{display:'flex',flexDirection:'column',gap:4}}>
          <label style={{fontSize:10,color:col('--t-text3'),fontFamily:mono,textTransform:'uppercase'}}>To</label>
          <input type='date' value={to} onChange={e=>setTo(e.target.value)} style={inpStyle}/>
        </div>
        {tab==='investors'&&<div style={{display:'flex',flexDirection:'column',gap:4}}>
          <label style={{fontSize:10,color:col('--t-text3'),fontFamily:mono,textTransform:'uppercase'}}>Top N</label>
          <select value={topN} onChange={e=>setTopN(Number(e.target.value))} style={selStyle}>
            {[5,10,20,50].map(n=><option key={n} value={n}>Top {n}</option>)}
          </select>
        </div>}
        <button onClick={load} style={{marginTop:18,padding:'8px 20px',background:col('--t-accent'),color:'#000',border:'none',borderRadius:7,fontWeight:700,fontSize:12,fontFamily:mono,cursor:'pointer'}}>
          Generate Report
        </button>
      </div>

      {/* Tabs */}
      <div style={{display:'flex',gap:4,marginBottom:20,borderBottom:`1px solid ${col('--t-border')}`}}>
        {TABS.map(t=>(
          <button key={t.id} onClick={()=>setTab(t.id)}
            style={{padding:'8px 16px',border:'none',cursor:'pointer',fontSize:12,fontFamily:mono,fontWeight:600,
              background:'transparent',borderBottom:tab===t.id?`2px solid ${col('--t-accent')}`:'2px solid transparent',
              color:tab===t.id?col('--t-accent'):col('--t-text3'),marginBottom:-1}}>{t.label}</button>
        ))}
      </div>

      {loading&&<div style={{color:col('--t-text3'),fontFamily:mono,fontSize:12}}>Generating report...</div>}

      {/* Orders Report */}
      {tab==='orders'&&data&&!loading&&(
        <div>
          <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:12,marginBottom:20}}>
            <Card label='Total Orders'  value={fmtN(data.totalOrders)}     color={col('--t-accent')}/>
            <Card label='Buy Orders'    value={fmtN(data.buyOrders)}       color='#00D4AA'/>
            <Card label='Sell Orders'   value={fmtN(data.sellOrders)}      color='#FF6B6B'/>
            <Card label='Total Value'   value={fmt(data.totalOrderValue)}  color='#FFB800'/>
          </div>
          <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:12,marginBottom:20}}>
            <Card label='Executed'  value={fmtN(data.executedOrders)}  color='#00D4AA'/>
            <Card label='Pending'   value={fmtN(data.pendingOrders)}   color='#FFB800'/>
            <Card label='Cancelled' value={fmtN(data.cancelledOrders)} color='#FF6B6B'/>
            <Card label='Rejected'  value={fmtN(data.rejectedOrders)}  color='#9B59B6'/>
          </div>
          <div style={{background:col('--t-panel'),border:`1px solid ${col('--t-border')}`,borderRadius:10,padding:20}}>
            <div style={{fontSize:12,fontWeight:700,fontFamily:mono,marginBottom:12}}>Order Summary — {data.fromDate?.slice(0,10)} to {data.toDate?.slice(0,10)}</div>
            <table style={{width:'100%',borderCollapse:'collapse',fontSize:12,fontFamily:mono}}>
              <thead><tr style={{borderBottom:`1px solid ${col('--t-border')}`}}>
                {['Metric','Count/Value'].map(h=><th key={h} style={{padding:'8px 12px',textAlign:'left',fontSize:10,color:col('--t-text3'),textTransform:'uppercase',fontWeight:600}}>{h}</th>)}
              </tr></thead>
              <tbody>
                {[['Total Orders',fmtN(data.totalOrders)],['Buy Orders',fmtN(data.buyOrders)],['Sell Orders',fmtN(data.sellOrders)],
                  ['Executed Orders',fmtN(data.executedOrders)],['Pending Orders',fmtN(data.pendingOrders)],
                  ['Cancelled Orders',fmtN(data.cancelledOrders)],['Rejected Orders',fmtN(data.rejectedOrders)],
                  ['Total Order Value',fmt(data.totalOrderValue)]].map(([label,val],i)=>(
                  <tr key={label} style={{borderBottom:`1px solid ${col('--t-border')}`,background:i%2===0?'transparent':'rgba(255,255,255,0.01)'}}>
                    <td style={{padding:'9px 12px',color:col('--t-text2')}}>{label}</td>
                    <td style={{padding:'9px 12px',fontWeight:700,color:col('--t-text1'),fontFamily:mono}}>{val}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Commission Report */}
      {tab==='commission'&&data&&!loading&&(
        <div>
          <div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:12,marginBottom:20}}>
            <Card label='Executed Orders'    value={fmtN(data.totalExecutedOrders)} color={col('--t-accent')}/>
            <Card label='Total Traded Value' value={fmt(data.totalTradedValue)}     color='#00D4AA'/>
            <Card label='Est. Commission'    value={fmt(data.estimatedCommission)}  color='#FFB800'/>
          </div>
          <div style={{background:col('--t-panel'),border:`1px solid ${col('--t-border')}`,borderRadius:10,padding:20}}>
            <div style={{fontSize:12,fontWeight:700,fontFamily:mono,marginBottom:12}}>Commission Report — {data.fromDate?.slice(0,10)} to {data.toDate?.slice(0,10)}</div>
            <div style={{fontSize:11,color:col('--t-text3'),marginBottom:12}}>Estimated at standard DSE commission rate (0.40% brokerage + 0.015% CDBL + 0.015% SECD)</div>
            <table style={{width:'100%',borderCollapse:'collapse',fontSize:12,fontFamily:mono}}>
              <thead><tr style={{borderBottom:`1px solid ${col('--t-border')}`}}>
                {['Component','Amount'].map(h=><th key={h} style={{padding:'8px 12px',textAlign:'left',fontSize:10,color:col('--t-text3'),textTransform:'uppercase',fontWeight:600}}>{h}</th>)}
              </tr></thead>
              <tbody>
                {[['Total Traded Value',fmt(data.totalTradedValue)],
                  ['Brokerage Commission (0.40%)',fmt(data.totalTradedValue*0.004)],
                  ['CDBL Fee (0.015%)',fmt(data.totalTradedValue*0.00015)],
                  ['SECD Fee (0.015%)',fmt(data.totalTradedValue*0.00015)],
                  ['VAT on Commission (15%)',fmt(data.totalTradedValue*0.004*0.15)],
                  ['Total Estimated Commission',fmt(data.estimatedCommission)]].map(([label,val],i)=>(
                  <tr key={label} style={{borderBottom:`1px solid ${col('--t-border')}`,background:i%2===0?'transparent':'rgba(255,255,255,0.01)'}}>
                    <td style={{padding:'9px 12px',color:col('--t-text2')}}>{label}</td>
                    <td style={{padding:'9px 12px',fontWeight:700,color:i===5?'#FFB800':col('--t-text1'),fontFamily:mono}}>{val}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Top Investors */}
      {tab==='investors'&&data&&!loading&&(
        <div style={{border:`1px solid ${col('--t-border')}`,borderRadius:10,overflow:'hidden'}}>
          <table style={{width:'100%',borderCollapse:'collapse',fontSize:12,fontFamily:mono}}>
            <thead><tr style={{background:col('--t-panel'),borderBottom:`1px solid ${col('--t-border')}`}}>
              {['Rank','Investor','Email','Total Orders','Executed','Traded Value'].map(h=>(
                <th key={h} style={{padding:'10px 14px',textAlign:'left',fontSize:10,color:col('--t-text3'),textTransform:'uppercase',fontWeight:600}}>{h}</th>
              ))}
            </tr></thead>
            <tbody>
              {(Array.isArray(data)?data:[]).map((inv,i)=>(
                <tr key={inv.investorId||i} style={{borderBottom:`1px solid ${col('--t-border')}`,background:i%2===0?'transparent':'rgba(255,255,255,0.01)'}}>
                  <td style={{padding:'10px 14px'}}>
                    <span style={{padding:'2px 8px',borderRadius:99,fontSize:10,fontWeight:700,fontFamily:mono,
                      background:i===0?'rgba(255,184,0,0.2)':i===1?'rgba(192,192,192,0.2)':i===2?'rgba(180,120,60,0.2)':'transparent',
                      color:i===0?'#FFB800':i===1?'#C0C0C0':i===2?'#B4783C':col('--t-text3')}}>
                      #{i+1}
                    </span>
                  </td>
                  <td style={{padding:'10px 14px',fontWeight:700}}>{inv.investorName}</td>
                  <td style={{padding:'10px 14px',color:col('--t-text3'),fontSize:11}}>{inv.email}</td>
                  <td style={{padding:'10px 14px',textAlign:'center'}}>{fmtN(inv.totalOrders)}</td>
                  <td style={{padding:'10px 14px',textAlign:'center',color:'#00D4AA'}}>{fmtN(inv.executedOrders)}</td>
                  <td style={{padding:'10px 14px',color:col('--t-accent'),fontWeight:700}}>{fmt(inv.totalTradedValue)}</td>
                </tr>
              ))}
              {(!Array.isArray(data)||data.length===0)&&<tr><td colSpan={6} style={{padding:24,textAlign:'center',color:col('--t-text3')}}>No investors found for this period.</td></tr>}
            </tbody>
          </table>
        </div>
      )}

      {/* Fund Requests Report */}
      {tab==='funds'&&data&&!loading&&(
        <div>
          <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:12,marginBottom:20}}>
            <Card label='Total Requests'    value={fmtN(data.totalRequests)}       color={col('--t-accent')}/>
            <Card label='Completed'         value={fmtN(data.completedRequests)}   color='#00D4AA'/>
            <Card label='Pending'           value={fmtN(data.pendingRequests)}     color='#FFB800'/>
            <Card label='Total Deposited'   value={fmt(data.totalCompletedAmount)} color='#64B4FF'/>
          </div>
          <div style={{background:col('--t-panel'),border:`1px solid ${col('--t-border')}`,borderRadius:10,padding:20}}>
            <div style={{fontSize:12,fontWeight:700,fontFamily:mono,marginBottom:12}}>Fund Request Report — {data.fromDate?.slice(0,10)} to {data.toDate?.slice(0,10)}</div>
            <table style={{width:'100%',borderCollapse:'collapse',fontSize:12,fontFamily:mono}}>
              <thead><tr style={{borderBottom:`1px solid ${col('--t-border')}`}}>
                {['Metric','Value'].map(h=><th key={h} style={{padding:'8px 12px',textAlign:'left',fontSize:10,color:col('--t-text3'),textTransform:'uppercase',fontWeight:600}}>{h}</th>)}
              </tr></thead>
              <tbody>
                {[['Total Requests',fmtN(data.totalRequests)],['Pending',fmtN(data.pendingRequests)],
                  ['Completed',fmtN(data.completedRequests)],['Rejected',fmtN(data.rejectedRequests)],
                  ['Total Completed Amount',fmt(data.totalCompletedAmount)]].map(([label,val],i)=>(
                  <tr key={label} style={{borderBottom:`1px solid ${col('--t-border')}`,background:i%2===0?'transparent':'rgba(255,255,255,0.01)'}}>
                    <td style={{padding:'9px 12px',color:col('--t-text2')}}>{label}</td>
                    <td style={{padding:'9px 12px',fontWeight:700,color:col('--t-text1'),fontFamily:mono}}>{val}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {!data&&!loading&&(
        <div style={{textAlign:'center',padding:48,color:col('--t-text3'),fontFamily:mono}}>
          <div style={{fontSize:32,marginBottom:12}}>📊</div>
          <div style={{fontSize:14,fontWeight:700,marginBottom:8}}>No Report Generated</div>
          <div style={{fontSize:12}}>Select a brokerage, date range and click Generate Report</div>
        </div>
      )}
    </div>
  );
}